COMMAND_CATALOG = {
    # ------------------------------------------------------------------ #
    # Admin / Channel
    # ------------------------------------------------------------------ #
    "channelinfo": {
        "category": "Admin",
        "usage": ".channelinfo [channel]",
        "args": "channel - channel mention, ID, or name (optional, defaults to current)",
        "example": ".channelinfo #general",
    },
    "textchannel": {
        "category": "Admin",
        "usage": ".textchannel <name>",
        "args": "name - name for the new text channel",
        "example": ".textchannel spam",
    },
    "voicechannel": {
        "category": "Admin",
        "usage": ".voicechannel <name>",
        "args": "name - name for the new voice channel",
        "example": ".voicechannel gaming",
    },
    "stagechannel": {
        "category": "Admin",
        "usage": ".stagechannel <name>",
        "args": "name - name for the new stage channel",
        "example": ".stagechannel talk",
    },
    "newschannel": {
        "category": "Admin",
        "usage": ".newschannel <name>",
        "args": "name - name for the new news channel",
        "example": ".newschannel announcements",
    },
    "thread": {
        "category": "Admin",
        "usage": ".thread <name>",
        "args": "name - name for the new thread",
        "example": ".thread discussion",
    },
    "category": {
        "category": "Admin",
        "usage": ".category <name>",
        "args": "name - name for the new category",
        "example": ".category Staff",
    },
    "deletecategory": {
        "category": "Admin",
        "usage": ".deletecategory <category_id>",
        "args": "category_id - ID of the category to delete",
        "example": ".deletecategory 123456789012345678",
    },
    "renamechannel": {
        "category": "Admin",
        "usage": ".renamechannel <channel> <name>",
        "args": "channel - target channel | name - new name",
        "example": ".renamechannel #general main-chat",
    },
    "deletechannel": {
        "category": "Admin",
        "usage": ".deletechannel <channel>",
        "args": "channel - channel mention, ID, or name",
        "example": ".deletechannel #spam",
    },
    "slowmode": {
        "category": "Admin",
        "usage": ".slowmode <channel> <seconds>",
        "args": "channel - target channel | seconds - slowmode duration (0-21600)",
        "example": ".slowmode #general 10",
    },
    "removeslowmode": {
        "category": "Admin",
        "usage": ".removeslowmode <channel>",
        "args": "channel - target channel",
        "example": ".removeslowmode #general",
    },
    "lockchannel": {
        "category": "Admin",
        "usage": ".lockchannel <channel>",
        "args": "channel - target channel",
        "example": ".lockchannel #general",
    },
    "unlockchannel": {
        "category": "Admin",
        "usage": ".unlockchannel <channel>",
        "args": "channel - target channel",
        "example": ".unlockchannel #general",
    },
    "purge": {
        "category": "Admin",
        "usage": ".purge <amount> [delay] [channel]",
        "args": "amount - number of messages | delay - optional delay between deletes | channel - optional target",
        "example": ".purge 50",
    },
    "purgeself": {
        "category": "Admin",
        "usage": ".purgeself <amount> [delay] [channel]",
        "args": "amount - number of your messages | delay - optional delay | channel - optional target",
        "example": ".purgeself 20",
    },
    "purgeuser": {
        "category": "Admin",
        "usage": ".purgeuser <amount> <user> [delay] [channel]",
        "args": "amount - number of messages | user - target user | delay - optional | channel - optional",
        "example": ".purgeuser 30 @baduser",
    },
    "purgerange": {
        "category": "Admin",
        "usage": ".purgerange <start> <end> [delay] [channel]",
        "args": "start/end - message links or IDs defining the range",
        "example": ".purgerange https://discord.com/channels/1/2/3 https://discord.com/channels/1/2/4",
    },
    "nuke": {
        "category": "Admin",
        "usage": ".nuke [channel]",
        "args": "channel - optional target channel (defaults to current)",
        "example": ".nuke #general",
    },
    "ackchannel": {
        "category": "Admin",
        "usage": ".ackchannel [channel]",
        "args": "channel - optional target channel",
        "example": ".ackchannel #general",
    },
    "ackmessage": {
        "category": "Admin",
        "usage": ".ackmessage <channel> <message_id>",
        "args": "channel - target channel | message_id - ID of the message to acknowledge",
        "example": ".ackmessage #general 123456789012345678",
    },
    "listwebhooks": {
        "category": "Admin",
        "usage": ".listwebhooks [channel]",
        "args": "channel - optional target text channel",
        "example": ".listwebhooks #general",
    },
    "createwebhook": {
        "category": "Admin",
        "usage": ".createwebhook [channel] [name]",
        "args": "channel - optional target | name - optional webhook name",
        "example": ".createwebhook #general ZNE Webhook",
    },
    "webhookinfo": {
        "category": "Admin",
        "usage": ".webhookinfo <url>",
        "args": "url - full webhook URL",
        "example": ".webhookinfo https://discord.com/api/webhooks/123/abc",
    },
    "webhooksend": {
        "category": "Admin",
        "usage": ".webhooksend <url> <message>",
        "args": "url - webhook URL | message - content to send",
        "example": ".webhooksend https://discord.com/api/webhooks/123/abc hello",
    },
    "webhookdelete": {
        "category": "Admin",
        "usage": ".webhookdelete <url>",
        "args": "url - full webhook URL",
        "example": ".webhookdelete https://discord.com/api/webhooks/123/abc",
    },
    "userinfo": {
        "category": "Admin",
        "usage": ".userinfo [user]",
        "args": "user - optional user mention, ID, or name (defaults to you)",
        "example": ".userinfo @someone",
    },
    "userage": {
        "category": "Admin",
        "usage": ".userage <user>",
        "args": "user - target user",
        "example": ".userage @someone",
    },
    "mutualfriends": {
        "category": "Admin",
        "usage": ".mutualfriends <user>",
        "args": "user - target user",
        "example": ".mutualfriends @someone",
    },
    "mutualservers": {
        "category": "Admin",
        "usage": ".mutualservers <user>",
        "args": "user - target user",
        "example": ".mutualservers @someone",
    },
    "platform": {
        "category": "Admin",
        "usage": ".platform [user]",
        "args": "user - optional user (defaults to you)",
        "example": ".platform @someone",
    },
    "avatar": {
        "category": "Admin",
        "usage": ".avatar <user>",
        "args": "user - target user",
        "example": ".avatar @someone",
    },
    "banner": {
        "category": "Admin",
        "usage": ".banner <user>",
        "args": "user - target user",
        "example": ".banner @someone",
    },
    "report": {
        "category": "Admin",
        "usage": ".report <message_link> <reason>",
        "args": "message_link - full message link | reason - reason for the report",
        "example": ".report https://discord.com/channels/1/2/3 spam",
    },
    "mute": {
        "category": "Admin",
        "usage": ".mute <user>",
        "args": "user - target member to mute",
        "example": ".mute @someone",
    },
    "unmute": {
        "category": "Admin",
        "usage": ".unmute <user>",
        "args": "user - target member to unmute",
        "example": ".unmute @someone",
    },
    "timeout": {
        "category": "Admin",
        "usage": ".timeout <user> <seconds>",
        "args": "user - target member | seconds - timeout duration (1-2419200)",
        "example": ".timeout @someone 3600",
    },
    "removetimeout": {
        "category": "Admin",
        "usage": ".removetimeout <user>",
        "args": "user - target member",
        "example": ".removetimeout @someone",
    },
    "kick": {
        "category": "Admin",
        "usage": ".kick <user> [reason]",
        "args": "user - target member | reason - optional kick reason",
        "example": ".kick @someone being rude",
    },
    "ban": {
        "category": "Admin",
        "usage": ".ban <user> [reason]",
        "args": "user - target member | reason - optional ban reason",
        "example": ".ban @someone broke rules",
    },
    "hackban": {
        "category": "Admin",
        "usage": ".hackban <user_id> [reason]",
        "args": "user_id - ID of user not in server | reason - optional",
        "example": ".hackban 123456789012345678",
    },
    "softban": {
        "category": "Admin",
        "usage": ".softban <user> [reason]",
        "args": "user - target member | reason - optional",
        "example": ".softban @someone",
    },
    "unban": {
        "category": "Admin",
        "usage": ".unban <user_id>",
        "args": "user_id - ID of banned user",
        "example": ".unban 123456789012345678",
    },
    "banlist": {
        "category": "Admin",
        "usage": ".banlist [server]",
        "args": "server - optional server ID or name",
        "example": ".banlist",
    },
    "copybans": {
        "category": "Admin",
        "usage": ".copybans <source> [dest]",
        "args": "source - source server ID/name | dest - optional destination (defaults to current)",
        "example": ".copybans 123456789012345678",
    },
    "nick": {
        "category": "Admin",
        "usage": ".nick <text>",
        "args": "text - new nickname, or 'none'/'clear' to reset",
        "example": ".nick CoolBot",
    },
    "nickuser": {
        "category": "Admin",
        "usage": ".nickuser <user> <text>",
        "args": "user - target member | text - new nickname",
        "example": ".nickuser @someone NewName",
    },
    "clearnick": {
        "category": "Admin",
        "usage": ".clearnick [user]",
        "args": "user - optional member (defaults to self)",
        "example": ".clearnick",
    },
    "serverinfo": {
        "category": "Admin",
        "usage": ".serverinfo [server]",
        "args": "server - optional server ID or name",
        "example": ".serverinfo",
    },
    "serverage": {
        "category": "Admin",
        "usage": ".serverage [server]",
        "args": "server - optional server ID or name",
        "example": ".serverage",
    },
    "serverowner": {
        "category": "Admin",
        "usage": ".serverowner [server]",
        "args": "server - optional server ID or name",
        "example": ".serverowner",
    },
    "servericon": {
        "category": "Admin",
        "usage": ".servericon [server]",
        "args": "server - optional server ID or name",
        "example": ".servericon",
    },
    "serverbanner": {
        "category": "Admin",
        "usage": ".serverbanner [server]",
        "args": "server - optional server ID or name",
        "example": ".serverbanner",
    },
    "serversplash": {
        "category": "Admin",
        "usage": ".serversplash [server]",
        "args": "server - optional server ID or name",
        "example": ".serversplash",
    },
    "serverdsplash": {
        "category": "Admin",
        "usage": ".serverdsplash [server]",
        "args": "server - optional server ID or name",
        "example": ".serverdsplash",
    },
    "serverboosters": {
        "category": "Admin",
        "usage": ".serverboosters [server]",
        "args": "server - optional server ID or name",
        "example": ".serverboosters",
    },
    "serverboostlevel": {
        "category": "Admin",
        "usage": ".serverboostlevel [server]",
        "args": "server - optional server ID or name",
        "example": ".serverboostlevel",
    },
    "setservername": {
        "category": "Admin",
        "usage": ".setservername <name>",
        "args": "name - new server name",
        "example": ".setservername My Server",
    },
    "setservericon": {
        "category": "Admin",
        "usage": ".setservericon <url>",
        "args": "url - direct image URL for the new icon",
        "example": ".setservericon https://example.com/icon.png",
    },
    "setserverbanner": {
        "category": "Admin",
        "usage": ".setserverbanner <url>",
        "args": "url - direct image URL for the new banner",
        "example": ".setserverbanner https://example.com/banner.png",
    },
    "lockserver": {
        "category": "Admin",
        "usage": ".lockserver [server]",
        "args": "server - optional server ID or name",
        "example": ".lockserver",
    },

    # ------------------------------------------------------------------ #
    # Animation
    # ------------------------------------------------------------------ #
    "virus": {
        "category": "Animation",
        "usage": ".virus [virus_name]",
        "args": "virus_name - trojan, worm, ransomware, or spyware (optional, random if omitted)",
        "example": ".virus trojan",
    },
    "100": {
        "category": "Animation",
        "usage": ".100",
        "args": "none",
        "example": ".100",
    },
    "bomb": {
        "category": "Animation",
        "usage": ".bomb",
        "args": "none",
        "example": ".bomb",
    },
    "fuckyou": {
        "category": "Animation",
        "usage": ".fuckyou",
        "args": "none",
        "example": ".fuckyou",
    },
    "fap": {
        "category": "Animation",
        "usage": ".fap",
        "args": "none",
        "example": ".fap",
    },
    "countup": {
        "category": "Animation",
        "usage": ".countup <number>",
        "args": "number - target number to count up to (1-1000)",
        "example": ".countup 50",
    },
    "countdown": {
        "category": "Animation",
        "usage": ".countdown <number>",
        "args": "number - starting number to count down from (1-1000)",
        "example": ".countdown 10",
    },
    "asciianimation": {
        "category": "Animation",
        "usage": ".asciianimation <text>",
        "args": "text - text to animate typing out",
        "example": ".asciianimation hello world",
    },
    "customanimationhelp": {
        "category": "Animation",
        "usage": ".customanimationhelp",
        "args": "none",
        "example": ".customanimationhelp",
    },
    "customanimations": {
        "category": "Animation",
        "usage": ".customanimations",
        "args": "none",
        "example": ".customanimations",
    },
    "customanimation": {
        "category": "Animation",
        "usage": ".customanimation <name>",
        "args": "name - name of a .txt file in the Animations folder",
        "example": ".customanimation wave",
    },

    # ------------------------------------------------------------------ #
    # Dump
    # ------------------------------------------------------------------ #
    "dumpall": {
        "category": "Dump",
        "usage": ".dumpall [channel]",
        "args": "channel - optional channel to dump (defaults to current)",
        "example": ".dumpall #general",
    },
    "dumpimages": {
        "category": "Dump",
        "usage": ".dumpimages [channel]",
        "args": "channel - optional channel (defaults to current)",
        "example": ".dumpimages #media",
    },
    "dumpvideos": {
        "category": "Dump",
        "usage": ".dumpvideos [channel]",
        "args": "channel - optional channel (defaults to current)",
        "example": ".dumpvideos #clips",
    },
    "dumpaudio": {
        "category": "Dump",
        "usage": ".dumpaudio [channel]",
        "args": "channel - optional channel (defaults to current)",
        "example": ".dumpaudio #music",
    },
    "dumptext": {
        "category": "Dump",
        "usage": ".dumptext [channel]",
        "args": "channel - optional channel (defaults to current)",
        "example": ".dumptext #files",
    },
    "dumpattachments": {
        "category": "Dump",
        "usage": ".dumpattachments [channel]",
        "args": "channel - optional channel (defaults to current)",
        "example": ".dumpattachments #general",
    },
    "dumpfiletype": {
        "category": "Dump",
        "usage": ".dumpfiletype <extension> [channel]",
        "args": "extension - file extension to dump | channel - optional",
        "example": ".dumpfiletype png #media",
    },
    "dumpcontenttype": {
        "category": "Dump",
        "usage": ".dumpcontenttype <content_type> [channel]",
        "args": "content_type - MIME content type | channel - optional",
        "example": ".dumpcontenttype image/png #media",
    },
    "dumpemojis": {
        "category": "Dump",
        "usage": ".dumpemojis [server]",
        "args": "server - optional server ID or name",
        "example": ".dumpemojis",
    },
    "dumpstickers": {
        "category": "Dump",
        "usage": ".dumpstickers [server]",
        "args": "server - optional server ID or name",
        "example": ".dumpstickers",
    },
    "dumpavatars": {
        "category": "Dump",
        "usage": ".dumpavatars [server]",
        "args": "server - optional server ID or name",
        "example": ".dumpavatars",
    },
    "dumpchannels": {
        "category": "Dump",
        "usage": ".dumpchannels [server]",
        "args": "server - optional server ID or name",
        "example": ".dumpchannels",
    },
    "dumpmembers": {
        "category": "Dump",
        "usage": ".dumpmembers [server]",
        "args": "server - optional server ID or name",
        "example": ".dumpmembers",
    },

    # ------------------------------------------------------------------ #
    # Encode
    # ------------------------------------------------------------------ #
    "rot13": {
        "category": "Encode",
        "usage": ".rot13 <text>",
        "args": "text - text to rotate 13 characters",
        "example": ".rot13 hello",
    },
    "hex": {
        "category": "Encode",
        "usage": ".hex <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".hex encode hello",
    },
    "binary": {
        "category": "Encode",
        "usage": ".binary <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".binary encode hello",
    },
    "base32": {
        "category": "Encode",
        "usage": ".base32 <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".base32 encode hello",
    },
    "base36": {
        "category": "Encode",
        "usage": ".base36 <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".base36 encode hello",
    },
    "base58": {
        "category": "Encode",
        "usage": ".base58 <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".base58 encode hello",
    },
    "base64": {
        "category": "Encode",
        "usage": ".base64 <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".base64 encode hello",
    },
    "base64url": {
        "category": "Encode",
        "usage": ".base64url <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".base64url encode hello",
    },
    "ascii85": {
        "category": "Encode",
        "usage": ".ascii85 <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".ascii85 encode hello",
    },
    "base85": {
        "category": "Encode",
        "usage": ".base85 <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".base85 encode hello",
    },
    "urlencode": {
        "category": "Encode",
        "usage": ".urlencode <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".urlencode encode hello world",
    },
    "morsecode": {
        "category": "Encode",
        "usage": ".morsecode <encode|decode> <text>",
        "args": "mode - encode or decode | text - input text",
        "example": ".morsecode encode hello",
    },
    "sha1": {
        "category": "Encode",
        "usage": ".sha1 <text>",
        "args": "text - text to hash",
        "example": ".sha1 password",
    },
    "sha224": {
        "category": "Encode",
        "usage": ".sha224 <text>",
        "args": "text - text to hash",
        "example": ".sha224 password",
    },
    "sha256": {
        "category": "Encode",
        "usage": ".sha256 <text>",
        "args": "text - text to hash",
        "example": ".sha256 password",
    },
    "sha384": {
        "category": "Encode",
        "usage": ".sha384 <text>",
        "args": "text - text to hash",
        "example": ".sha384 password",
    },
    "sha512": {
        "category": "Encode",
        "usage": ".sha512 <text>",
        "args": "text - text to hash",
        "example": ".sha512 password",
    },
    "blake2b": {
        "category": "Encode",
        "usage": ".blake2b <text>",
        "args": "text - text to hash",
        "example": ".blake2b password",
    },
    "blake2s": {
        "category": "Encode",
        "usage": ".blake2s <text>",
        "args": "text - text to hash",
        "example": ".blake2s password",
    },
    "adler32": {
        "category": "Encode",
        "usage": ".adler32 <text>",
        "args": "text - text to hash",
        "example": ".adler32 hello",
    },
    "crc32": {
        "category": "Encode",
        "usage": ".crc32 <text>",
        "args": "text - text to hash",
        "example": ".crc32 hello",
    },
    "crc64": {
        "category": "Encode",
        "usage": ".crc64 <text>",
        "args": "text - text to hash",
        "example": ".crc64 hello",
    },
    "fnv32": {
        "category": "Encode",
        "usage": ".fnv32 <text>",
        "args": "text - text to hash",
        "example": ".fnv32 hello",
    },
    "fnv64": {
        "category": "Encode",
        "usage": ".fnv64 <text>",
        "args": "text - text to hash",
        "example": ".fnv64 hello",
    },
    "fnv128": {
        "category": "Encode",
        "usage": ".fnv128 <text>",
        "args": "text - text to hash",
        "example": ".fnv128 hello",
    },
    "aes128": {
        "category": "Encode",
        "usage": '.aes128 <encrypt|decrypt> "key" "text"',
        "args": 'mode - encrypt or decrypt | key - 16-byte key in quotes | text - text in quotes',
        "example": '.aes128 encrypt "mysecretkey1234" "secret message"',
    },
    "aes192": {
        "category": "Encode",
        "usage": '.aes192 <encrypt|decrypt> "key" "text"',
        "args": 'mode - encrypt or decrypt | key - 24-byte key in quotes | text - text in quotes',
        "example": '.aes192 encrypt "mysecretkey123456789012" "secret message"',
    },
    "aes256": {
        "category": "Encode",
        "usage": '.aes256 <encrypt|decrypt> "key" "text"',
        "args": 'mode - encrypt or decrypt | key - 32-byte key in quotes | text - text in quotes',
        "example": '.aes256 encrypt "mysecretkey12345678901234567890" "secret message"',
    },

    # ------------------------------------------------------------------ #
    # Fun
    # ------------------------------------------------------------------ #
    "eightball": {
        "category": "Fun",
        "usage": ".eightball <question>",
        "args": "question - any yes/no question",
        "example": ".eightball will I win the lottery?",
    },
    "howgay": {
        "category": "Fun",
        "usage": ".howgay [user]",
        "args": "user - optional target (defaults to you)",
        "example": ".howgay @someone",
    },
    "howsimp": {
        "category": "Fun",
        "usage": ".howsimp [user]",
        "args": "user - optional target (defaults to you)",
        "example": ".howsimp @someone",
    },
    "penis": {
        "category": "Fun",
        "usage": ".penis [user]",
        "args": "user - optional target (defaults to you)",
        "example": ".penis @someone",
    },
    "ego": {
        "category": "Fun",
        "usage": ".ego [user]",
        "args": "user - optional target (defaults to you)",
        "example": ".ego @someone",
    },
    "iqtest": {
        "category": "Fun",
        "usage": ".iqtest [user]",
        "args": "user - optional target (defaults to you)",
        "example": ".iqtest @someone",
    },
    "hack": {
        "category": "Fun",
        "usage": ".hack [user]",
        "args": "user - optional target (defaults to you)",
        "example": ".hack @someone",
    },
    "insult": {
        "category": "Fun",
        "usage": ".insult [text]",
        "args": "text - ignored argument, for flavor only",
        "example": ".insult",
    },
    "dadjoke": {
        "category": "Fun",
        "usage": ".dadjoke",
        "args": "none",
        "example": ".dadjoke",
    },
    "yomomma": {
        "category": "Fun",
        "usage": ".yomomma",
        "args": "none",
        "example": ".yomomma",
    },
    "wouldyourather": {
        "category": "Fun",
        "usage": ".wouldyourather",
        "args": "none",
        "example": ".wouldyourather",
    },
    "topic": {
        "category": "Fun",
        "usage": ".topic",
        "args": "none",
        "example": ".topic",
    },
    "slot": {
        "category": "Fun",
        "usage": ".slot",
        "args": "none",
        "example": ".slot",
    },
    "advice": {
        "category": "Fun",
        "usage": ".advice",
        "args": "none",
        "example": ".advice",
    },
    "catfact": {
        "category": "Fun",
        "usage": ".catfact",
        "args": "none",
        "example": ".catfact",
    },
    "dogfact": {
        "category": "Fun",
        "usage": ".dogfact",
        "args": "none",
        "example": ".dogfact",
    },
    "pandafact": {
        "category": "Fun",
        "usage": ".pandafact",
        "args": "none",
        "example": ".pandafact",
    },
    "foxfact": {
        "category": "Fun",
        "usage": ".foxfact",
        "args": "none",
        "example": ".foxfact",
    },
    "koalafact": {
        "category": "Fun",
        "usage": ".koalafact",
        "args": "none",
        "example": ".koalafact",
    },
    "birdfact": {
        "category": "Fun",
        "usage": ".birdfact",
        "args": "none",
        "example": ".birdfact",
    },
    "redpandafact": {
        "category": "Fun",
        "usage": ".redpandafact",
        "args": "none",
        "example": ".redpandafact",
    },
    "whalefact": {
        "category": "Fun",
        "usage": ".whalefact",
        "args": "none",
        "example": ".whalefact",
    },
    "kangaroofact": {
        "category": "Fun",
        "usage": ".kangaroofact",
        "args": "none",
        "example": ".kangaroofact",
    },
    "bunnyfact": {
        "category": "Fun",
        "usage": ".bunnyfact",
        "args": "none",
        "example": ".bunnyfact",
    },
    "lionfact": {
        "category": "Fun",
        "usage": ".lionfact",
        "args": "none",
        "example": ".lionfact",
    },
    "frogfact": {
        "category": "Fun",
        "usage": ".frogfact",
        "args": "none",
        "example": ".frogfact",
    },
    "duckfact": {
        "category": "Fun",
        "usage": ".duckfact",
        "args": "none",
        "example": ".duckfact",
    },
    "penguinfact": {
        "category": "Fun",
        "usage": ".penguinfact",
        "args": "none",
        "example": ".penguinfact",
    },
    "dolphinfact": {
        "category": "Fun",
        "usage": ".dolphinfact",
        "args": "none",
        "example": ".dolphinfact",
    },
    "bearfact": {
        "category": "Fun",
        "usage": ".bearfact",
        "args": "none",
        "example": ".bearfact",
    },
    "axolotlfact": {
        "category": "Fun",
        "usage": ".axolotlfact",
        "args": "none",
        "example": ".axolotlfact",
    },
    "capybarafact": {
        "category": "Fun",
        "usage": ".capybarafact",
        "args": "none",
        "example": ".capybarafact",
    },
    "trivia": {
        "category": "Fun",
        "usage": ".trivia",
        "args": "none",
        "example": ".trivia",
    },
    "dice": {
        "category": "Fun",
        "usage": ".dice [XdY|sides]",
        "args": "arg - optional NdM format (e.g. 2d20) or number of sides",
        "example": ".dice 2d6",
    },
    "randomemoji": {
        "category": "Fun",
        "usage": ".randomemoji",
        "args": "none",
        "example": ".randomemoji",
    },
    "randomchannel": {
        "category": "Fun",
        "usage": ".randomchannel",
        "args": "none",
        "example": ".randomchannel",
    },
    "choose": {
        "category": "Fun",
        "usage": ".choose <options>",
        "args": "options - comma or space separated list",
        "example": ".choose pizza, burgers, sushi",
    },
    "poll": {
        "category": "Fun",
        "usage": ".poll <question>",
        "args": "question - poll question",
        "example": ".poll What should we eat?",
    },
    "numberfact": {
        "category": "Fun",
        "usage": ".numberfact <number>",
        "args": "number - a number for a trivia fact",
        "example": ".numberfact 42",
    },
    "joke": {
        "category": "Fun",
        "usage": ".joke",
        "args": "none",
        "example": ".joke",
    },
    "fml": {
        "category": "Fun",
        "usage": ".fml",
        "args": "none",
        "example": ".fml",
    },
    "tronald": {
        "category": "Fun",
        "usage": ".tronald",
        "args": "none",
        "example": ".tronald",
    },
    "kanyewest": {
        "category": "Fun",
        "usage": ".kanyewest",
        "args": "none",
        "example": ".kanyewest",
    },
    "rps": {
        "category": "Fun",
        "usage": ".rps <rock|paper|scissors>",
        "args": "choice - rock, paper, or scissors (also r/p/s)",
        "example": ".rps rock",
    },
    "covidtest": {
        "category": "Fun",
        "usage": ".covidtest [user]",
        "args": "user - optional target (defaults to you)",
        "example": ".covidtest @someone",
    },
    "hug": {
        "category": "Fun",
        "usage": ".hug <user>",
        "args": "user - target user to hug",
        "example": ".hug @someone",
    },
    "kiss": {
        "category": "Fun",
        "usage": ".kiss <user>",
        "args": "user - target user to kiss",
        "example": ".kiss @someone",
    },
    "slap": {
        "category": "Fun",
        "usage": ".slap <user>",
        "args": "user - target user to slap",
        "example": ".slap @someone",
    },
    "cuddle": {
        "category": "Fun",
        "usage": ".cuddle <user>",
        "args": "user - target user to cuddle",
        "example": ".cuddle @someone",
    },
    "pat": {
        "category": "Fun",
        "usage": ".pat <user>",
        "args": "user - target user to pat",
        "example": ".pat @someone",
    },
    "feed": {
        "category": "Fun",
        "usage": ".feed <user>",
        "args": "user - target user to feed",
        "example": ".feed @someone",
    },
    "wink": {
        "category": "Fun",
        "usage": ".wink <user>",
        "args": "user - target user to wink at",
        "example": ".wink @someone",
    },
    "chucknorris": {
        "category": "Fun",
        "usage": ".chucknorris",
        "args": "none",
        "example": ".chucknorris",
    },
    "iss": {
        "category": "Fun",
        "usage": ".iss",
        "args": "none",
        "example": ".iss",
    },
    "apod": {
        "category": "Fun",
        "usage": ".apod",
        "args": "none",
        "example": ".apod",
    },
    "httpcat": {
        "category": "Fun",
        "usage": ".httpcat <status>",
        "args": "status - HTTP status code (100-599)",
        "example": ".httpcat 404",
    },
    "riddle": {
        "category": "Fun",
        "usage": ".riddle",
        "args": "none",
        "example": ".riddle",
    },
    "quote": {
        "category": "Fun",
        "usage": ".quote",
        "args": "none",
        "example": ".quote",
    },
    "evilinsult": {
        "category": "Fun",
        "usage": ".evilinsult",
        "args": "none",
        "example": ".evilinsult",
    },
    "owoify": {
        "category": "Fun",
        "usage": ".owoify <text>",
        "args": "text - text to owoify",
        "example": ".owoify hello there",
    },
    "uwuify": {
        "category": "Fun",
        "usage": ".uwuify <text>",
        "args": "text - text to uwuify",
        "example": ".uwuify hello there",
    },
    "uvuify": {
        "category": "Fun",
        "usage": ".uvuify <text>",
        "args": "text - text to uvuify",
        "example": ".uvuify hello there",
    },

    # ------------------------------------------------------------------ #
    # Text
    # ------------------------------------------------------------------ #
    "empty": {
        "category": "Text",
        "usage": ".empty",
        "args": "none",
        "example": ".empty",
    },
    "reverse": {
        "category": "Text",
        "usage": ".reverse <text>",
        "args": "text - text to reverse",
        "example": ".reverse hello",
    },
    "alphabet": {
        "category": "Text",
        "usage": ".alphabet",
        "args": "none",
        "example": ".alphabet",
    },
    "ascii": {
        "category": "Text",
        "usage": ".ascii <text>",
        "args": "text - text to render as ASCII art (requires pyfiglet)",
        "example": ".ascii ZNE",
    },
    "bold": {
        "category": "Text",
        "usage": ".bold <text>",
        "args": "text - text to bold",
        "example": ".bold hello",
    },
    "strike": {
        "category": "Text",
        "usage": ".strike <text>",
        "args": "text - text to strikethrough",
        "example": ".strike hello",
    },
    "italic": {
        "category": "Text",
        "usage": ".italic <text>",
        "args": "text - text to italicize",
        "example": ".italic hello",
    },
    "spoiler": {
        "category": "Text",
        "usage": ".spoiler <text>",
        "args": "text - text to spoiler",
        "example": ".spoiler surprise ending",
    },
    "lspoiler": {
        "category": "Text",
        "usage": ".lspoiler <text>",
        "args": "text - text to letter-spoiler",
        "example": ".lspoiler secret",
    },
    "leet": {
        "category": "Text",
        "usage": ".leet <text>",
        "args": "text - text to convert to leetspeak",
        "example": ".leet hello",
    },
    "devowel": {
        "category": "Text",
        "usage": ".devowel <text>",
        "args": "text - text to remove vowels from",
        "example": ".devowel hello",
    },
    "edit": {
        "category": "Text",
        "usage": ".edit <text>",
        "args": "text - text to type out word by word",
        "example": ".edit hello world this is a test",
    },
    "emojify": {
        "category": "Text",
        "usage": ".emojify <text>",
        "args": "text - text to convert to regional indicator emojis",
        "example": ".emojify hello",
    },
    "shrug": {
        "category": "Text",
        "usage": ".shrug [text]",
        "args": "text - optional text before the shrug",
        "example": ".shrug whatever",
    },
    "lenny": {
        "category": "Text",
        "usage": ".lenny",
        "args": "none",
        "example": ".lenny",
    },
    "tableflip": {
        "category": "Text",
        "usage": ".tableflip",
        "args": "none",
        "example": ".tableflip",
    },
    "unflip": {
        "category": "Text",
        "usage": ".unflip",
        "args": "none",
        "example": ".unflip",
    },
    "clap": {
        "category": "Text",
        "usage": ".clap <text>",
        "args": "text - text to clap between words",
        "example": ".clap this is important",
    },
    "zalgo": {
        "category": "Text",
        "usage": ".zalgo <text>",
        "args": "text - text to corrupt with zalgo marks",
        "example": ".zalgo hello",
    },
    "unzalgo": {
        "category": "Text",
        "usage": ".unzalgo <text>",
        "args": "text - zalgo text to clean",
        "example": ".unzalgo h̸e̷l̷l̸o̷",
    },
    "upper": {
        "category": "Text",
        "usage": ".upper <text>",
        "args": "text - text to uppercase",
        "example": ".upper hello",
    },
    "lower": {
        "category": "Text",
        "usage": ".lower <text>",
        "args": "text - text to lowercase",
        "example": ".lower HELLO",
    },
    "fliptext": {
        "category": "Text",
        "usage": ".fliptext <text>",
        "args": "text - text to flip upside down",
        "example": ".fliptext hello",
    },
    "unfliptext": {
        "category": "Text",
        "usage": ".unfliptext <text>",
        "args": "text - flipped text to unflip",
        "example": ".unfliptext oʅʅʅǝɥ",
    },
    "wave": {
        "category": "Text",
        "usage": ".wave <text>",
        "args": "text - text to wave-case",
        "example": ".wave hello world",
    },
    "customwave": {
        "category": "Text",
        "usage": ".customwave <width> <iterations> <text>",
        "args": "width - letters per wave | iterations - repeats | text - text to wave",
        "example": ".customwave 2 1 hello world",
    },
    "zwc": {
        "category": "Text",
        "usage": ".zwc <text>",
        "args": "text - text to hide with zero-width characters",
        "example": ".zwc secret message",
    },
    "distance": {
        "category": "Text",
        "usage": '.distance "string one" "string two"',
        "args": "two quoted strings to compare",
        "example": '.distance "kitten" "sitting"',
    },
    "codeblock": {
        "category": "Text",
        "usage": ".codeblock [language] <code>",
        "args": "language - optional language hint | code - code to format",
        "example": ".codeblock python print('hi')",
    },
    "ping": {
        "category": "Utility",
        "usage": ".ping",
        "args": "none",
        "example": ".ping",
    },
    "uptime": {
        "category": "Utility",
        "usage": ".uptime",
        "args": "none",
        "example": ".uptime",
    },
    "servercount": {
        "category": "Utility",
        "usage": ".servercount",
        "args": "none",
        "example": ".servercount",
    },
    "say": {
        "category": "Utility",
        "usage": ".say <text>",
        "args": "text - message to send",
        "example": ".say Hello World",
    },
    "calc": {
        "category": "Utility",
        "usage": ".calc <expression>",
        "args": "expression - math expression to evaluate",
        "example": ".calc 2+2*3",
    },
    "b64encode": {
        "category": "Utility",
        "usage": ".b64encode <text>",
        "args": "text - text to encode",
        "example": ".b64encode Hello",
    },
    "b64decode": {
        "category": "Utility",
        "usage": ".b64decode <text>",
        "args": "text - base64 to decode",
        "example": ".b64decode SGVsbG8=",
    },
    "charcount": {
        "category": "Utility",
        "usage": ".charcount <text>",
        "args": "text - text to count",
        "example": ".charcount Hello World",
    },
    "remind": {
        "category": "Utility",
        "usage": ".remind <time> <text>",
        "args": "time - duration (5s, 10m, 2h, 1d) | text - reminder message",
        "example": ".remind 5m Check the oven",
    },
    "define": {
        "category": "Utility",
        "usage": ".define <word>",
        "args": "word - word to define",
        "example": ".define serendipity",
    },
    "botinfo": {
        "category": "Utility",
        "usage": ".botinfo",
        "args": "none",
        "example": ".botinfo",
    },
    "afk": {
        "category": "Utility",
        "usage": ".afk [reason]",
        "args": "reason - optional AFK reason",
        "example": ".afk Sleeping",
    },
    "myid": {
        "category": "Selfbot",
        "usage": ".myid",
        "args": "none",
        "example": ".myid",
    },
    "purgebot": {
        "category": "Selfbot",
        "usage": ".purgebot [limit]",
        "args": "limit - number of messages to scan (default 50)",
        "example": ".purgebot 100",
    },
    "massreact": {
        "category": "Selfbot",
        "usage": ".massreact <emoji> [limit]",
        "args": "emoji - reaction emoji | limit - messages to react to (default 10)",
        "example": ".massreact 👍 20",
    },
    "ghostping": {
        "category": "Selfbot",
        "usage": ".ghostping <@user>",
        "args": "user - member to ghost ping",
        "example": ".ghostping @someone",
    },
    "setstatus": {
        "category": "Selfbot",
        "usage": ".setstatus <status> [text]",
        "args": "status - online/idle/dnd/invisible | text - optional status text",
        "example": ".setstatus dnd Coding...",
    },
    "setactivity": {
        "category": "Selfbot",
        "usage": ".setactivity <type> [text]",
        "args": "type - playing/watching/listening/competing | text - activity text",
        "example": ".setactivity playing Visual Studio Code",
    },
    "clearactivity": {
        "category": "Selfbot",
        "usage": ".clearactivity",
        "args": "none",
        "example": ".clearactivity",
    },
    "setnick": {
        "category": "Selfbot",
        "usage": ".setnick <nickname>",
        "args": "nickname - new nickname",
        "example": ".setnick CoolName",
    },
    "emojilist": {
        "category": "Selfbot",
        "usage": ".emojilist",
        "args": "none",
        "example": ".emojilist",
    },
    "rolelist": {
        "category": "Selfbot",
        "usage": ".rolelist",
        "args": "none",
        "example": ".rolelist",
    },
    "channellist": {
        "category": "Selfbot",
        "usage": ".channellist",
        "args": "none",
        "example": ".channellist",
    },
    "snowflake": {
        "category": "Selfbot",
        "usage": ".snowflake <id>",
        "args": "id - Discord snowflake ID",
        "example": ".snowflake 123456789012345678",
    },
}
